name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

innoweb:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    jobs:
      mysql:
        image: mysqlclient:2.1.1
        env:
          MYSQL_ROOT_PASSWORD: innosoft-2022
          MYSQL_DATABASE: innosoftdb
        ports: ['3307:3307']

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python $
      uses: actions/setup-python@v2
      with:
        python-version: $
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: $
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: $
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: decide/coverage.xml 
