name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    name: Test Suite with PHPUnit
    runs-on: ubuntu-20.04

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: secret
          MYSQL_DATABASE: evidentia
          MYSQL_USER: evidentia
          MYSQL_PASSWORD: secret
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
      
    steps:
    - uses: actions/checkout@v2
    - name: Verify MySQL connection from host
      run: |
        mysql --host 127.0.0.1 --port 3306 -uroot -psecret -e "GRANT ALL ON *.*  TO 'evidentia'@'%' identified by 'secret'; FLUSH PRIVILEGES;"
        mysql --host 127.0.0.1 --port 3306 -uroot -psecret -e "CREATE DATABASE base21;"
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE innosoftdb;' -uroot -proot
        mysql --host localhost --port 3307 -uroot -proot -e "GRANT ALL ON *.*  TO 'innosoft'@'localhost' identified by 'innosoft'; FLUSH PRIVILEGES;"
        
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: 3306
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: 3306
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: decide/coverage.xml
