name: Django CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.10]

    services:
      mysql:
        image: mysql:8.0.1
        env:
          DB_DATABASE: innosoftdb
          DB_USER: innosoft
          DB_PASSWORD: 'innosoft-2022'
          DB_HOST: 127.0.0.1
      
    steps:
    - uses: actions/checkout@v2
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE innosoftdb;' -uinnosoft -pinnosoft-2022
    - name: Set up Python 3.10.5
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.5
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py migrate
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: 3306
    - name: Run Tests
      run: |
        python manage.py test
      env: 
        DBENGINE: django.db.backends.mysql
        DBNAME: innosoftdb
        DBUSER: innosoft
        DBPASSWORD: innosoft-2022
        DBHOST: 127.0.0.1
        DBPORT: 3307
    - name: Codacy Coverage Reporter
      uses: codacy/codacy-coverage-reporter-action@v1
      with:
          project-token: ${{ secrets.CODACY_TOKEN }}
          coverage-reports: decide/coverage.xml 
